name: E2E tests scheduled or dispatched

run-name: ${{ github.event_name == 'schedule' && format('Run e2e test scheduled - {0}', github.event.schedule) || github.event_name == 'workflow_dispatch' && format('Run e2e test for branch - {0}', github.ref) || github.head_ref || github.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 8 * * 3' # Every Wednesday at 08:00 UTC
  workflow_dispatch:
    inputs:
      platform:
        description: Platform of mobile application
        required: true
        type: choice
        default: ios
        options:
          - ios
          - android
jobs:
  e2e-tests:
    if: ${{ github.ref || 'refs/heads/main' }}
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build, and e2e for ios platform
        if: ${{ github.event_name == 'schedule' || inputs.platform == 'ios' }}
        uses: ./.github/actions/e2e-ios
        with:
          ref: ${{ github.ref }}
